version: '3.1'
services:
 maven-web-app:
  image: vikash463/spring-boot-mongo:1
  environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=user1
    - MONGO_DB_PASSWORD=passwd
  container_name: springboot
  ports:
    - 8083:8080
  working_dir: /opt/test
  depends_on:
   - mongo
  networks:
   - springappnetwork
  deploy:
   replicas: 2
   update_config:
    parallelism: 1
    delay: 10s
   restart_policy:
    condition: on-failure
    delay: 20s
    max_attempts: 3

 mongo:
  image: mongo
  container_name: mongo
  environment:
   - MONGO_INITDB_ROOT_USERNAME=user1
   - MONGO_INITDB_ROOT_PASSWORD=passwd
  volumes:
   - spring-vol:/data/db
  networks:
   - springappnetwork


volumes:
 spring-vol:
  driver: local
networks:
 springappnetwork:
  driver: overlay
